
version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=protik
      - POSTGRES_PASSWORD=112233
      - POSTGRES_DB=geoloc
    ports:
      - 5432:5432
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - mynet
    hostname: 'localhost'

  app:
    build: .
    #   volume specification is needed for hot reload support other wise hot reload
    #   wont trigger
    volumes:
      # volume allocation only for Dev as it is required for Air
      - ./:/usr/src/app/
      - /etc/localtime:/etc/localtime:ro

    ports:
      - '8000:8000'
    depends_on:
      - postgres
    networks:
      - mynet

volumes:
  database_postgres:
networks:
  mynet:
